#!/bin/bash

echo "Simple Calculator Menu:"
echo "a. Addition"
echo "s. Subtraction"
echo "m. Multiplication"
echo "d. Division"
echo "q. Quit"

read -p "Enter your choice (a/s/m/d/q): " choice

 if [[ "$choice" == "q" ]]; then
    echo "Thank you"
    exit 0


 elif [[ "$choice" == "a" || "$choice" == "s" || "$choice" == "m" || "$choice" == "d" ]]; then
    read -p "Enter first number: " num1
    read -p "Enter second number: " num2

    case "$choice" in
      a)result=$(echo "$num1 + $num2" | bc)
        ;;
      s)
        result=$(echo "$num1 - $num2" | bc)
        ;;
      m)
        result=$(echo "$num1 * $num2" | bc)
        ;;
      d)
        if [ $num2 -lt 0 ]; then
         echo "Error: Division by zero is not allowed."
         continue
        fi
        result=$(echo "$num1 / $num2" | bc)
        ;;
    esac

    echo "Result: $result"
 else
    echo "Invalid choice. Please select a valid option (a/s/m/d/q)."
 fi

